# Generated by Django 5.1.5 on 2025-01-31 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('provider_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('provider_name', models.CharField(max_length=20)),
                ('provider_info', models.CharField(max_length=50)),
                ('provider_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(max_length=20)),
                ('total', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.providers')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
