# Generated by Django 5.1.5 on 2025-01-23 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('income_id', models.UUIDField(default=uuid.UUID('e46f1349-4fb8-42f9-a24e-6cd1368574b8'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('time_frame', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_income',
            },
        ),
    ]
