# Generated by Django 5.1.5 on 2025-01-23 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='income',
            name='income_id',
            field=models.UUIDField(default=uuid.UUID('8b5fe66e-0db0-4f1d-91bf-44e39043fdfd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
