# Generated by Django 5.1.5 on 2025-01-23 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_user_id_income_user_alter_income_income_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
