# Generated by Django 5.1.5 on 2025-01-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_income_income_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='amount',
            new_name='income_amount',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='name',
            new_name='income_name',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='type',
            new_name='income_type',
        ),
    ]
