# Generated by Django 5.1.5 on 2025-02-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_income_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
